   
server:
<<<<<<< HEAD
 port: ${PORT:${SERVER_PORT:0}}
=======
  port: ${PORT:${SERVER_PORT:0}}
>>>>>>> d1b7a411b38ebd4bc42194877b278007252c2dad


spring:
  application:
    name: api-catalog

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}
