server:
  port: ${PORT:${SERVER_PORT:0}}
  # port: 8081
spring:
  application:
    name: api-movie
  datasource:
    driverClassName: com.mysql.cj.Driver
    url: cj:mysql://localhost:3306/movie-dev
    username: localhost
    password: Pomelo22
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka

